"""
Qwen3.5-DeltaCoder-9B — Unsloth DPO training script (v1.1).
Loads the merged v1 model from HuggingFace, trains a DPO LoRA adapter on
preference pairs generated by generate_dpo_pairs.py.

Usage:
    # Quick test (50 steps, verify loss moves before full run):
    python scripts/train_dpo.py --max-steps 50

    # Full training:
    python scripts/train_dpo.py
"""

# IMPORTANT: PatchDPOTrainer must be called BEFORE importing DPOTrainer from trl
from unsloth import FastVisionModel, PatchDPOTrainer

PatchDPOTrainer()

import argparse
import json
import pathlib
from datasets import Dataset
from trl import DPOTrainer, DPOConfig


# ---------- Patch UnslothDPOTrainer for text-only DPO ----------
# Qwen3.5 is a VLM so Unsloth generates a vision code path in the DPO trainer.
# The cache file is now written by the DPOTrainer import above — patch it now
# before DPOTrainer is instantiated.
def _patch_unsloth_dpo_cache():
    cache_file = pathlib.Path("unsloth_compiled_cache/UnslothDPOTrainer.py")
    if not cache_file.exists():
        print("WARNING: UnslothDPOTrainer cache not found, skipping patch")
        return

    content = cache_file.read_text()
    patches = {
        # Remove images= arg from processor call
        'processed_features = processor(images=features["images"], text=features["prompt"], add_special_tokens=False)': 'processed_features = tokenizer(features["prompt"], add_special_tokens=False)',
        # Remove pixel_values extraction
        'pixel_values = processed_features["pixel_values"][0]': "pixel_values = None  # text-only DPO",
        # Remove pixel_values from return dict
        '"pixel_values": pixel_values,': '# "pixel_values": pixel_values,  # text-only DPO',
    }

    patched = False
    for old, new in patches.items():
        if old in content:
            content = content.replace(old, new)
            patched = True

    if patched:
        cache_file.write_text(content)
        # Delete pycache so Python uses the patched .py file
        import shutil

        pycache = pathlib.Path("unsloth_compiled_cache/__pycache__")
        if pycache.exists():
            shutil.rmtree(pycache)
        print("Patched UnslothDPOTrainer for text-only DPO")
    else:
        print("UnslothDPOTrainer already patched or pattern not found")


_patch_unsloth_dpo_cache()

# ---------- Config ----------
MODEL_NAME = "Qwen/Qwen3.5-9B"
MAX_SEQ_LENGTH = 4096
LORA_R = 32
LORA_ALPHA = 32


def parse_args():
    parser = argparse.ArgumentParser(description="DPO training for DeltaCoder v1.1")
    parser.add_argument(
        "--max-steps",
        type=int,
        default=-1,
        help="Override epochs with a fixed step count (e.g. 50 for a quick test run)",
    )
    parser.add_argument(
        "--data",
        type=str,
        default="data/dpo_pairs.jsonl",
        help="Path to DPO pairs JSONL in conversational format",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./outputs/deltacoder-9b-dpo",
        help="Output directory for checkpoints and final adapter",
    )
    return parser.parse_args()


def load_dpo_dataset(path: str) -> Dataset:
    """Load conversational-format JSONL into a HuggingFace Dataset."""
    records = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    print(f"Loaded {len(records)} preference pairs from {path}")
    return Dataset.from_list(records)


def main():
    args = parse_args()

    # ---------- Load model ----------
    print("Loading model...")
    model, tokenizer = FastVisionModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=False,
        load_in_16bit=True,
        full_finetuning=False,
        trust_remote_code=True,
    )

    # ---------- LoRA ----------
    print("Applying LoRA (r=32)...")
    model = FastVisionModel.get_peft_model(
        model,
        finetune_vision_layers=False,  # text-only DPO
        finetune_language_layers=True,
        finetune_attention_modules=True,
        finetune_mlp_modules=True,
        r=LORA_R,
        lora_alpha=LORA_ALPHA,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )

    # ---------- Dataset ----------
    print("Loading DPO pairs...")
    dataset = load_dpo_dataset(args.data)

    # ---------- DPO Config ----------
    dpo_config_kwargs = dict(
        beta=0.1,
        loss_type="sigmoid",
        max_length=MAX_SEQ_LENGTH,
        max_prompt_length=1024,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=16,
        num_train_epochs=1,
        learning_rate=5e-6,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        optim="adamw_torch",
        logging_steps=5,
        save_strategy="steps",
        save_steps=0.5,
        save_total_limit=2,
        output_dir=args.output_dir,
        seed=3407,
        report_to="none",
    )

    if args.max_steps > 0:
        dpo_config_kwargs["max_steps"] = args.max_steps

    dpo_config = DPOConfig(**dpo_config_kwargs)

    # Use plain tokenizer — FastVisionModel returns a processor for Qwen3.5 VLM
    # which breaks text-only DPO dataset preparation.
    from transformers import AutoTokenizer

    plain_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)

    # ---------- Trainer ----------
    print("Setting up DPO trainer...")
    trainer = DPOTrainer(
        model=model,
        ref_model=None,
        args=dpo_config,
        train_dataset=dataset,
        processing_class=plain_tokenizer,
    )

    # ---------- Train ----------
    n_steps = args.max_steps if args.max_steps > 0 else "full epoch"
    print(f"Starting DPO training ({len(dataset)} pairs, {n_steps} steps)...")
    print(f"  LR: 5e-6  |  beta: 0.1  |  effective batch: 16  |  r: {LORA_R}")
    print("  Watch: rewards/chosen should increase, rewards/rejected should decrease")

    trainer_stats = trainer.train()

    # ---------- Save ----------
    adapter_path = f"{args.output_dir}/lora_adapter"
    print(f"Saving LoRA adapter to {adapter_path}...")
    model.save_pretrained(adapter_path)
    tokenizer.save_pretrained(adapter_path)

    print(f"\nDone! Training stats: {trainer_stats}")


if __name__ == "__main__":
    main()
